name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: mkdir build1

    - name: Build React app
      run: cd build1 && echo "hello" > test.txt

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts-1
        path: build1
  config:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts-1

    - name: Install dependencies
      run: mkdir build2

    - name: Build React app
      run: cd build2 && echo "hello" > test1.txt

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-2
        path: build2

  deploy:
    runs-on: ubuntu-latest
    needs: config

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v5
      with:
        name: build-artifacts-2

    - name: Copy build folder to self-hosted runner
      run: |
        ls
        pwd
        #cp -R ${{ github.workspace }}/build/* C:\Users\Administrator\Desktop
